/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 *******************************************************************************/

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.20 at 04:05:47 PM CDT 
//


package org.apache.wink.common.internal.providers.jaxb.jaxb1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.wink.common.internal.providers.jaxb.jaxb1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddNumbers_QNAME = new QName("http://org/apache/wink/common/internal/providers/jaxb/jaxb1", "addNumbers");
    private final static QName _MyPojo_QNAME = new QName("http://org/apache/wink/common/internal/providers/jaxb/jaxb1", "myPojo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.wink.common.internal.providers.jaxb.jaxb1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddNumbers }
     * 
     */
    public AddNumbers createAddNumbers() {
        return new AddNumbers();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddNumbers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org/apache/wink/common/internal/providers/jaxb/jaxb1", name = "addNumbers")
    public JAXBElement<AddNumbers> createAddNumbers(AddNumbers value) {
        return new JAXBElement<AddNumbers>(_AddNumbers_QNAME, AddNumbers.class, null, value);
    }
    
    /**
     * Create an instance of {@link MyPojo }
     * 
     */
    public MyPojo createMyPojo() {
        return new MyPojo();
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MyPojo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org/apache/wink/common/internal/providers/jaxb/jaxb1", name = "MyPojo")
    public JAXBElement<MyPojo> createMyPojo(MyPojo value) {
        return new JAXBElement<MyPojo>(_MyPojo_QNAME, MyPojo.class, null, value);
    }


}
