/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-456 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.20 at 10:55:05 AM IST 
//

package org.apache.wink.common.model.rss;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.apache.wink.common.model.rss package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SkipDays_QNAME  = new QName("", "skipDays"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _SkipHours_QNAME = new QName("", "skipHours"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Source_QNAME    = new QName("", "source"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Cloud_QNAME     = new QName("", "cloud"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Enclosure_QNAME = new QName("", "enclosure"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Channel_QNAME   = new QName("", "channel"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Guid_QNAME      = new QName("", "guid"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _TextInput_QNAME = new QName("", "textInput"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Item_QNAME      = new QName("", "item"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Image_QNAME     = new QName("", "image"); //$NON-NLS-1$ //$NON-NLS-2$
    private final static QName _Category_QNAME  = new QName("", "category"); //$NON-NLS-1$ //$NON-NLS-2$

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.apache.wink.common.model.rss
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RssSkipDays}
     */
    public RssSkipDays createRssSkipDays() {
        return new RssSkipDays();
    }

    /**
     * Create an instance of {@link RssSkipHours}
     */
    public RssSkipHours createRssSkipHours() {
        return new RssSkipHours();
    }

    /**
     * Create an instance of {@link RssSource}
     */
    public RssSource createRssSource() {
        return new RssSource();
    }

    /**
     * Create an instance of {@link RssCloud}
     */
    public RssCloud createRssCloud() {
        return new RssCloud();
    }

    /**
     * Create an instance of {@link RssEnclosure}
     */
    public RssEnclosure createRssEnclosure() {
        return new RssEnclosure();
    }

    /**
     * Create an instance of {@link RssChannel}
     */
    public RssChannel createRssChannel() {
        return new RssChannel();
    }

    /**
     * Create an instance of {@link RssGuid}
     */
    public RssGuid createRssGuid() {
        return new RssGuid();
    }

    /**
     * Create an instance of {@link RssTextInput}
     */
    public RssTextInput createRssTextInput() {
        return new RssTextInput();
    }

    /**
     * Create an instance of {@link RssItem}
     */
    public RssItem createRssItem() {
        return new RssItem();
    }

    /**
     * Create an instance of {@link RssImage}
     */
    public RssImage createRssImage() {
        return new RssImage();
    }

    /**
     * Create an instance of {@link RssCategory}
     */
    public RssCategory createRssCategory() {
        return new RssCategory();
    }

    /**
     * Create an instance of {@link RssFeed}
     */
    public RssFeed createRssFeed() {
        return new RssFeed();
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssSkipDays}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "skipDays")
    public JAXBElement<RssSkipDays> createRssSkipDays(RssSkipDays value) {
        return new JAXBElement<RssSkipDays>(_SkipDays_QNAME, RssSkipDays.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssSkipHours}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "skipHours")
    public JAXBElement<RssSkipHours> createRssSkipHours(RssSkipHours value) {
        return new JAXBElement<RssSkipHours>(_SkipHours_QNAME, RssSkipHours.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssSource}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "source")
    public JAXBElement<RssSource> createRssSource(RssSource value) {
        return new JAXBElement<RssSource>(_Source_QNAME, RssSource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssCloud}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "cloud")
    public JAXBElement<RssCloud> createRssCloud(RssCloud value) {
        return new JAXBElement<RssCloud>(_Cloud_QNAME, RssCloud.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssEnclosure}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "enclosure")
    public JAXBElement<RssEnclosure> createRssEnclosure(RssEnclosure value) {
        return new JAXBElement<RssEnclosure>(_Enclosure_QNAME, RssEnclosure.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssChannel}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "channel")
    public JAXBElement<RssChannel> createRssChannel(RssChannel value) {
        return new JAXBElement<RssChannel>(_Channel_QNAME, RssChannel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssGuid}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "guid")
    public JAXBElement<RssGuid> createRssGuid(RssGuid value) {
        return new JAXBElement<RssGuid>(_Guid_QNAME, RssGuid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssTextInput}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "textInput")
    public JAXBElement<RssTextInput> createRssTextInput(RssTextInput value) {
        return new JAXBElement<RssTextInput>(_TextInput_QNAME, RssTextInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssItem}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "item")
    public JAXBElement<RssItem> createRssItem(RssItem value) {
        return new JAXBElement<RssItem>(_Item_QNAME, RssItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssImage}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "image")
    public JAXBElement<RssImage> createRssImage(RssImage value) {
        return new JAXBElement<RssImage>(_Image_QNAME, RssImage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement} {@code <} {@link RssCategory}
     * {@code >}
     */
    @XmlElementDecl(namespace = "", name = "category")
    public JAXBElement<RssCategory> createRssCategory(RssCategory value) {
        return new JAXBElement<RssCategory>(_Category_QNAME, RssCategory.class, null, value);
    }

}
