/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.24 at 01:47:17 PM IDT 
//

package org.apache.wink.common.internal.model.admin;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element name=&quot;uri&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot;/&gt;
 *         &lt;element name=&quot;class-name&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;priority&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}decimal&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;workspace&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element name=&quot;collection&quot; type=&quot;{http://www.w3.org/2001/XMLSchema}string&quot; minOccurs=&quot;0&quot;/&gt;
 *         &lt;element ref=&quot;{http://apache.org/wink/common/internal/model/admin}methods&quot;/&gt;
 *         &lt;element ref=&quot;{http://apache.org/wink/common/internal/model/admin}sub-resources&quot;/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"uri", "className", "priority", "workspace", "collection",
                                 "methods", "subResources"})
@XmlRootElement(name = "resource")
public class Resource {

    @XmlElement(required = true)
    protected String       uri;
    @XmlElement(name = "class-name")
    protected String       className;
    protected BigDecimal   priority;
    protected String       workspace;
    protected String       collection;
    @XmlElement(required = true)
    protected Methods      methods;
    @XmlElement(name = "sub-resources", required = true)
    protected SubResources subResources;

    /**
     * Gets the value of the uri property.
     * 
     * @return possible object is {@link String }
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return possible object is {@link String }
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return possible object is {@link BigDecimal }
     */
    public BigDecimal getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value allowed object is {@link BigDecimal }
     */
    public void setPriority(BigDecimal value) {
        this.priority = value;
    }

    /**
     * Gets the value of the workspace property.
     * 
     * @return possible object is {@link String }
     */
    public String getWorkspace() {
        return workspace;
    }

    /**
     * Sets the value of the workspace property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setWorkspace(String value) {
        this.workspace = value;
    }

    /**
     * Gets the value of the collection property.
     * 
     * @return possible object is {@link String }
     */
    public String getCollection() {
        return collection;
    }

    /**
     * Sets the value of the collection property.
     * 
     * @param value allowed object is {@link String }
     */
    public void setCollection(String value) {
        this.collection = value;
    }

    /**
     * Gets the value of the methods property.
     * 
     * @return possible object is {@link Methods }
     */
    public Methods getMethods() {
        return methods;
    }

    /**
     * Sets the value of the methods property.
     * 
     * @param value allowed object is {@link Methods }
     */
    public void setMethods(Methods value) {
        this.methods = value;
    }

    /**
     * Gets the value of the subResources property.
     * 
     * @return possible object is {@link SubResources }
     */
    public SubResources getSubResources() {
        return subResources;
    }

    /**
     * Sets the value of the subResources property.
     * 
     * @param value allowed object is {@link SubResources }
     */
    public void setSubResources(SubResources value) {
        this.subResources = value;
    }

}
