/*******************************************************************************
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *  
 *   http://www.apache.org/licenses/LICENSE-2.0
 *  
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *  
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.17 at 09:44:59 AM IDT  
//

package org.apache.wink.common.model.opensearch;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.apache.wink.common.model.opensearch
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Image_QNAME                 =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Image");
    private final static QName _ItemsPerPage_QNAME          =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "itemsPerPage");
    private final static QName _ShortName_QNAME             =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "ShortName");
    private final static QName _TotalResults_QNAME          =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "totalResults");
    private final static QName _Query_QNAME                 =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Query");
    private final static QName _Developer_QNAME             =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Developer");
    private final static QName _OpenSearchDescription_QNAME =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "OpenSearchDescription");
    private final static QName _Contact_QNAME               =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Contact");
    private final static QName _Attribution_QNAME           =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Attribution");
    private final static QName _SyndicationRight_QNAME      =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "SyndicationRight");
    private final static QName _Tags_QNAME                  =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Tags");
    private final static QName _Language_QNAME              =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Language");
    private final static QName _OutputEncoding_QNAME        =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "OutputEncoding");
    private final static QName _InputEncoding_QNAME         =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "InputEncoding");
    private final static QName _Url_QNAME                   =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Url");
    private final static QName _StartIndex_QNAME            =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "startIndex");
    private final static QName _LongName_QNAME              =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "LongName");
    private final static QName _Description_QNAME           =
                                                                new QName(
                                                                          "http://a9.com/-/spec/opensearch/1.1/",
                                                                          "Description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * org.apache.wink.common.model.opensearch
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OpenSearchUrl }
     */
    public OpenSearchUrl createOpenSearchUrl() {
        return new OpenSearchUrl();
    }

    /**
     * Create an instance of {@link OpenSearchImage }
     */
    public OpenSearchImage createOpenSearchImage() {
        return new OpenSearchImage();
    }

    /**
     * Create an instance of {@link OpenSearchDescription }
     */
    public OpenSearchDescription createOpenSearchDescription() {
        return new OpenSearchDescription();
    }

    /**
     * Create an instance of {@link OpenSearchQuery }
     */
    public OpenSearchQuery createOpenSearchQuery() {
        return new OpenSearchQuery();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSearchImage }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Image")
    public JAXBElement<OpenSearchImage> createImage(OpenSearchImage value) {
        return new JAXBElement<OpenSearchImage>(_Image_QNAME, OpenSearchImage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "itemsPerPage")
    public JAXBElement<BigInteger> createItemsPerPage(BigInteger value) {
        return new JAXBElement<BigInteger>(_ItemsPerPage_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "ShortName")
    public JAXBElement<String> createShortName(String value) {
        return new JAXBElement<String>(_ShortName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "totalResults")
    public JAXBElement<BigInteger> createTotalResults(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalResults_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSearchQuery }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Query")
    public JAXBElement<OpenSearchQuery> createQuery(OpenSearchQuery value) {
        return new JAXBElement<OpenSearchQuery>(_Query_QNAME, OpenSearchQuery.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Developer")
    public JAXBElement<String> createDeveloper(String value) {
        return new JAXBElement<String>(_Developer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}
     * {@link OpenSearchDescription }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "OpenSearchDescription")
    public JAXBElement<OpenSearchDescription> createOpenSearchDescription(OpenSearchDescription value) {
        return new JAXBElement<OpenSearchDescription>(_OpenSearchDescription_QNAME,
                                                      OpenSearchDescription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Contact")
    public JAXBElement<String> createContact(String value) {
        return new JAXBElement<String>(_Contact_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Attribution")
    public JAXBElement<String> createAttribution(String value) {
        return new JAXBElement<String>(_Attribution_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "SyndicationRight", defaultValue = "open")
    public JAXBElement<String> createSyndicationRight(String value) {
        return new JAXBElement<String>(_SyndicationRight_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Tags")
    public JAXBElement<String> createTags(String value) {
        return new JAXBElement<String>(_Tags_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Language")
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "OutputEncoding", defaultValue = "UTF-8")
    public JAXBElement<String> createOutputEncoding(String value) {
        return new JAXBElement<String>(_OutputEncoding_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "InputEncoding", defaultValue = "UTF-8")
    public JAXBElement<String> createInputEncoding(String value) {
        return new JAXBElement<String>(_InputEncoding_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSearchUrl }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Url")
    public JAXBElement<OpenSearchUrl> createUrl(OpenSearchUrl value) {
        return new JAXBElement<OpenSearchUrl>(_Url_QNAME, OpenSearchUrl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
     * {@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "startIndex")
    public JAXBElement<BigInteger> createStartIndex(BigInteger value) {
        return new JAXBElement<BigInteger>(_StartIndex_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "LongName")
    public JAXBElement<String> createLongName(String value) {
        return new JAXBElement<String>(_LongName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://a9.com/-/spec/opensearch/1.1/", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

}
